# Whyzr hosted app.
#
# git is a runtime dependency, not a build tool: every child gets a real git
# branch and worktree, and journal entries are real commits.

# DELIBERATE DEVIATION from WHYZR-HANDOFF-3 section 5, which specifies
# node:22-slim. The lockfile is generated by npm 11, and node:22-slim ships
# npm 10, which rejects it with "Missing: ... from lock file" and fails the
# build. The handoff's real requirement is `npm ci`, never `npm install`,
# and that is honoured below. Node 24 also matches the development runtime.
FROM node:24-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends git ca-certificates \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# npm ci, never npm install: install rewrites package-lock.json, which the
# eval runner then refuses as a dirty tree.
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

COPY . .

# On boot the app makes a BARE clone of itself on the volume and adds one
# worktree per child off it, so the image must contain a valid git repo.
# Rebuild the repo state inside the image rather than relying on whatever
# .git the build context carried.
RUN git config --global user.email "whyzr@localhost" \
  && git config --global user.name "Whyzr" \
  && git config --global --add safe.directory /app

# Persistent volume: the agent repo, child worktrees, registry, transcripts.
# Worktrees are filesystem state, so this volume is load-bearing: without it
# every child's branch is gone on redeploy.
ENV WHYZR_DATA_DIR=/data
VOLUME ["/data"]

# Run as a non-root user that can still write /data and /app.
RUN useradd --create-home --uid 10001 whyzr \
  && mkdir -p /data \
  && chown -R whyzr:whyzr /app /data
USER whyzr

ENV NODE_ENV=production
ENV PORT=3456
EXPOSE 3456

HEALTHCHECK --interval=30s --timeout=5s --start-period=20s \
  CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||3456)+'/healthz').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

CMD ["node", "server/app.mjs"]
